from django.db import models

from .enums import Genre, Mood, Occasion
from .library import Library


class Song(models.Model):
    """
    The core artifact generated by the system.
    Belongs to one Library. Has exactly one Genre, Mood, and Occasion.
    Matches domain class: Song.
    """
    library        = models.ForeignKey(
        Library,
        on_delete=models.CASCADE,
        related_name='songs'
    )
    title          = models.CharField(max_length=255)
    duration       = models.PositiveIntegerField(help_text="Duration in seconds.")
    genre          = models.CharField(max_length=20, choices=Genre.choices)
    mood           = models.CharField(max_length=20, choices=Mood.choices)
    occasion       = models.CharField(max_length=20, choices=Occasion.choices)
    date_generated = models.DateTimeField(auto_now_add=True)
    is_deleted     = models.BooleanField(
        default=False,
        help_text="Soft delete flag — hidden from Library without DB removal."
    )

    class Meta:
        ordering = ['-date_generated']
        verbose_name = "Song"

    def __str__(self):
        return f"{self.title} ({self.genre} / {self.mood})"
