# Generated by Django 6.0.3 on 2026-03-20 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('generation_quota', models.PositiveIntegerField(default=10, help_text='Daily generation limit for this creator.')),
            ],
            options={
                'verbose_name': 'Creator',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='domain.creator')),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Libraries',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds.')),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('hiphop', 'Hip-Hop'), ('jazz', 'Jazz'), ('country', 'Country')], max_length=20)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('energetic', 'Energetic'), ('calm', 'Calm')], max_length=20)),
                ('occasion', models.CharField(choices=[('workout', 'Workout'), ('funeral', 'Funeral'), ('celebration', 'Celebration'), ('relaxation', 'Relaxation')], max_length=20)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag — hidden from Library without DB removal.')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='domain.library')),
            ],
            options={
                'verbose_name': 'Song',
                'ordering': ['-date_generated'],
            },
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('recently_played', models.ManyToManyField(blank=True, help_text='Songs this listener has recently played.', related_name='listened_by', to='domain.song')),
            ],
            options={
                'verbose_name': 'Listener',
            },
        ),
    ]
