# Generated by Django 6.0.3 on 2026-04-12 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.URLField(blank=True, help_text='URL of the generated audio file.', null=True),
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='Unique task identifier returned by the generation strategy.', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TEXT_SUCCESS', 'Text Success'), ('FIRST_SUCCESS', 'First Success'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=30)),
                ('strategy_used', models.CharField(choices=[('mock', 'Mock'), ('suno', 'Suno')], max_length=10)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('stream_audio_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='domain.song')),
            ],
            options={
                'verbose_name': 'Generation Job',
                'ordering': ['-created_at'],
            },
        ),
    ]
