# Generated by Django 6.0.3 on 2026-04-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_song_audio_url_generationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='prompt',
            field=models.TextField(blank=True, default='', help_text='Original prompt used for generation (stored for regeneration).'),
        ),
        migrations.AddField(
            model_name='song',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='User rating from 1 to 5 stars.', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='style',
            field=models.CharField(blank=True, default='', help_text='Original style used for generation (stored for regeneration).', max_length=200),
        ),
    ]
